import { useMemo, useState } from 'react'
import { HiCheck, HiRefresh, HiSparkles } from 'react-icons/hi'
import { useAcademyStore } from '../store/academyStore'
import { isCardDue, useFlashcardDeck } from '../hooks/useFlashcardDeck'

export function FlashcardsPage() {
  const { allCards, cardSchedule, dueCards, nextDueInDays } = useFlashcardDeck()
  const {flashcardStatus,setFlashcardStatus}=useAcademyStore(); const [batchIds,setBatchIds]=useState([]); const [round,setRound]=useState({}); const [index,setIndex]=useState(0); const [flipped,setFlipped]=useState(false)
  // "Bilaman" deb belgilangan karta butunlay chetlanmaydi — rejalashtirilgan
  // sanasi (dueAt) kelganda takrorlash to'plamiga qaytadi (spaced repetition).
  const initialIds=useMemo(()=>{const review=dueCards.filter(card=>flashcardStatus[card.id]==='review');const fresh=dueCards.filter(card=>!flashcardStatus[card.id]);const dueKnown=dueCards.filter(card=>flashcardStatus[card.id]==='known');return [...review,...fresh,...dueKnown].slice(0,20).map(card=>card.id)},[dueCards,flashcardStatus])
  const activeIds=batchIds.length?batchIds:initialIds; const batch=activeIds.map(id=>allCards.find(card=>card.id===id)).filter(Boolean); const card=batch[index]
  // Joriy to'plam birinchi javobdayoq muzlatiladi: aks holda "Bilaman" bosilgan karta to'plamdan chiqib ketib, hisob 0 ga qaytadi.
  const answer=status=>{if(!batchIds.length)setBatchIds(activeIds);setFlashcardStatus(card.id,status);const nextRound={...round,[card.id]:status};const finished=batch.every(item=>nextRound[item.id]);if(!finished){const nextIndex=batch.findIndex((item,position)=>position>index&&!nextRound[item.id]);setRound(nextRound);setIndex(nextIndex===-1?batch.findIndex(item=>!nextRound[item.id]):nextIndex);setFlipped(false);return}const reviewIds=batch.filter(item=>nextRound[item.id]==='review').map(item=>item.id);if(reviewIds.length){setBatchIds(reviewIds);setRound({});setIndex(0);setFlipped(false);return}const remaining=allCards.filter(item=>!activeIds.includes(item.id)&&isCardDue(cardSchedule[item.id]));const next=[...remaining.filter(item=>flashcardStatus[item.id]==='review'),...remaining.filter(item=>!flashcardStatus[item.id]),...remaining.filter(item=>flashcardStatus[item.id]==='known')].slice(0,20).map(item=>item.id);setBatchIds(next);setRound({});setIndex(0);setFlipped(false)}
  if(!allCards.length)return <div className="card-panel p-12 text-center"><HiSparkles className="mx-auto h-10 w-10 text-emerald-500"/><h1 className="mt-4 text-xl font-bold">Kartalar hali shakllanmadi</h1><p className="mt-2 text-sm text-slate-500">Darsni yakunlang yoki test ishlang.</p></div>
  if(!card)return <div className="card-panel p-12 text-center"><HiCheck className="mx-auto h-12 w-12 text-emerald-500"/><h1 className="mt-4 text-2xl font-black">Bugungi kartalar tugadi</h1><p className="mt-2 text-slate-500">Yangi dars yoki test xatosi paydo bo‘lsa, keyingi to‘plam avtomatik yaratiladi. "Bilaman" deb belgilangan kartalar ham o‘z vaqtida takrorlash uchun qaytib keladi.</p>{nextDueInDays&&<p className="mt-3 text-sm font-semibold text-emerald-600">Keyingi karta {nextDueInDays} kundan so‘ng takrorlash uchun qaytadi.</p>}</div>
  const known=batch.filter(item=>round[item.id]==='known').length
  const totalKnown=allCards.filter(item=>flashcardStatus[item.id]==='known').length
  return <div className="space-y-6"><section className="hero-panel"><p className="eyebrow">Aqlli flesh-kartalar</p><h1 className="page-title">20 talik o‘rganish to‘plami</h1><p className="mt-2 text-sm text-slate-500">Avval qiyin kartalar takrorlanadi. "Bilaman" deb belgilangan kartalar ham unutilmasligi uchun kunlar o‘tgach qaytadi (spaced repetition).</p></section><div className="card-panel flex min-h-[520px] flex-col items-center justify-center p-6"><div className="mb-5 flex w-full max-w-2xl justify-between text-sm"><span className="pill bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10">{card.subject}</span><span className="text-right text-slate-400">{index+1}/{batch.length} · O‘zlashtirildi: <b className="text-emerald-600">{known}/{batch.length}</b><span className="block text-xs">Jami: {totalKnown}/{allCards.length} karta</span></span></div><button onClick={()=>setFlipped(value=>!value)} className="flashcard relative w-full max-w-2xl text-left"><div className={`flashcard-inner ${flipped?'is-flipped':''}`}><div className="flashcard-face bg-slate-900 text-white"><HiSparkles className="mb-8 h-8 w-8 text-emerald-400"/><p className="text-xs uppercase tracking-widest text-slate-400">Savol</p><h2 className="mt-4 text-2xl font-semibold">{card.front}</h2></div><div className="flashcard-face flashcard-back bg-emerald-500 text-white"><HiCheck className="mb-8 h-8 w-8"/><p className="text-xs uppercase tracking-widest text-emerald-100">Javob</p><h2 className="mt-4 text-2xl font-semibold">{card.back}</h2></div></div></button><div className="mt-6 flex w-full max-w-2xl justify-center gap-3"><button onClick={()=>answer('review')} className="btn-review"><HiRefresh/> Yana takrorlayman</button><button onClick={()=>answer('known')} className="btn-primary"><HiCheck/> Bilaman</button></div><div className="mt-6 h-2 w-full max-w-2xl overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-emerald-500 transition-all" style={{width:`${Object.keys(round).length/batch.length*100}%`}}/></div></div></div>
}
