import { Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { FiArrowRight, FiBookOpen, FiCheckCircle, FiClock, FiTarget, FiTrendingUp } from 'react-icons/fi'
import { useUserStore } from '../store/useUserStore'

export function HomePage() {
  const { t } = useTranslation()
  const name = useUserStore(state => state.profile.name.split(' ')[0])
  const highlights = [[FiClock,'realExam','realExamText'],[FiTrendingUp,'clearProgress','clearProgressText'],[FiTarget,'mixedControl','mixedControlText']]
  return <div className="space-y-6 sm:space-y-8">
    <section className="relative overflow-hidden rounded-[28px] bg-slate-950 px-5 py-8 text-white sm:rounded-[32px] sm:px-10 sm:py-12 lg:px-14 lg:py-16"><div className="absolute -right-20 -top-20 h-80 w-80 rounded-full bg-emerald-500/25 blur-3xl"/><div className="absolute bottom-0 right-1/3 h-52 w-52 rounded-full bg-blue-500/20 blur-3xl"/><div className="relative max-w-3xl"><span className="pill bg-white/10 text-emerald-300">{t('system')}</span><h1 className="mt-5 text-3xl font-black leading-tight sm:mt-6 sm:text-5xl">{t('welcome',{name})}</h1><p className="mt-3 text-lg font-semibold text-slate-100 sm:mt-4 sm:text-xl">{t('todaySubject')}</p><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300 sm:text-base sm:leading-7">{t('homeDescription')}</p><div className="mt-6 grid grid-cols-2 gap-3 sm:mt-8 sm:flex sm:flex-wrap"><Link to="/subjects" className="btn-primary col-span-2 px-6">{t('chooseSubject')} <FiArrowRight/></Link><Link to="/profile" className="btn-secondary bg-white/10 text-white hover:bg-white/20">{t('profileButton')}</Link><Link to="/results" className="btn-secondary bg-white/10 text-white hover:bg-white/20">{t('myResults')}</Link></div><div className="mt-6 flex flex-wrap gap-x-6 gap-y-2 text-sm text-slate-300 sm:mt-9 sm:gap-7">{['activeSubjects','testEveryThree','finalMock'].map(key=><span key={key} className="flex items-center gap-2"><FiCheckCircle className="text-emerald-400"/>{t(key)}</span>)}</div></div></section>
    <section><div className="flex items-end justify-between"><div><p className="eyebrow">{t('startLearning')}</p><h2 className="mt-2 text-2xl font-black">{t('textbookToExam')}</h2></div><Link to="/subjects" className="hidden items-center gap-2 text-sm font-bold text-emerald-600 sm:flex">{t('allSubjects')} <FiArrowRight/></Link></div><div className="mt-4 grid gap-3 sm:mt-5 sm:gap-5 md:grid-cols-3">{highlights.map(([Icon,title,text])=><article key={title} className="card-panel flex gap-4 p-4 sm:p-6 md:block"><span className="icon-box bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10"><Icon/></span><div className="min-w-0"><h3 className="font-bold md:mt-5">{t(title)}</h3><p className="mt-1 text-sm leading-6 text-slate-500 md:mt-2">{t(text)}</p></div></article>)}</div></section>
    <section className="rounded-[28px] bg-gradient-to-r from-emerald-600 to-teal-700 p-6 text-white sm:rounded-[32px] sm:p-8 sm:flex sm:items-center sm:justify-between"><div><FiBookOpen className="h-9 w-9 text-emerald-100"/><h2 className="mt-4 text-2xl font-black">{t('ready')}</h2><p className="mt-2 text-emerald-50">{t('readyText')}</p></div><Link to="/subjects" className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 font-bold text-emerald-700 sm:mt-0 sm:inline-flex sm:w-auto">{t('start')} <FiArrowRight/></Link></section>
  </div>
}
